# Generated by Django 5.2.3 on 2025-06-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctorprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
